version: 0.2
phases:
  build:
    commands:
      - aws deploy push --application-name cicdapp --s3-location s3://cicd-handson-ec2build/artifact.zip --source src
artifacts:
  files:
    - '**/*'
  base-directory: src